### Create a new Report
Post http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 1982,
    "milage": 50000,
    "lng": 45,
    "lat": 45,
    "price": 20000
}

### Create a new Report
PATCH http://localhost:3000/reports/25
Content-Type: application/json

{
    "approved": true
}

### Get all reports
Get http://localhost:3000/reports

### Get an estimate for existing vechiles
Get http://localhost:3000/reports/getEstimate?make=Ford&model=Mustang&lng=45&lat=45&milage=20000&year=1981